#!/bin/bash

# 🔍 Firebase Security Rules Kontrol Scripti
# Bu script Firebase projenizdeki güvenlik kurallarını kontrol etmeniz için rehber sağlar

echo "🔥 Firebase Security Rules Kontrol Rehberi"
echo "=========================================="
echo ""
echo "📍 Adım 1: Firebase Console'a gidin"
echo "   https://console.firebase.google.com/"
echo ""
echo "📍 Adım 2: 'drumly-mobile' projesini seçin"
echo ""
echo "📍 Adım 3: Sol menüden 'Firestore Database' veya 'Realtime Database' seçin"
echo ""
echo "📍 Adım 4: 'Rules' sekmesine tıklayın"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ GÜVENLI RULES (Önerilen):"
echo ""
echo "rules_version = '2';"
echo "service cloud.firestore {"
echo "  match /databases/{database}/documents {"
echo "    match /{document=**} {"
echo "      allow read, write: if request.auth != null;"
echo "    }"
echo "  }"
echo "}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "❌ TEHLİKELİ RULES (Değiştirin!):"
echo ""
echo "allow read, write: if true;  // ← HERKESİN ERİŞİMİ VAR!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 Adım 5: Storage Rules (Eğer kullanıyorsanız)"
echo ""
echo "rules_version = '2';"
echo "service firebase.storage {"
echo "  match /b/{bucket}/o {"
echo "    match /{allPaths=**} {"
echo "      allow read, write: if request.auth != null;"
echo "    }"
echo "  }"
echo "}"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📍 Adım 6: Billing & Usage Alarms Kurun"
echo ""
echo "   1. Firebase Console → Usage and billing"
echo "   2. 'Set a budget' tıklayın"
echo "   3. Günlük limit: $10"
echo "   4. Email alarm ekleyin"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ Kontrol tamamlandı!"
echo ""
read -p "Firebase Security Rules'u kontrol ettiniz mi? (y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "✅ Harika! Artık daha güvenlisiniz."
else
    echo "⚠️  Lütfen en kısa sürede kontrol edin!"
fi
